apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: convoy-tls
  namespace: convoy
spec:
  secretName: convoy-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - convoy.inevitable.fyi
